### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jiemingy**
Hi,

I just open this pull request, and ask for your comments. But I haven't completed my project, and I will let you know when I complete it. 

Bests,
Jieming

### CODE REVIEW

**Review by emmoramor — COMMENTED** [review]
Hi Jieming,

Thanks for the opportunity to review your project. My first batch of comments below...

Regarding your answer to 1(a)...  you proposed "spatially coextensive with" as a property that should have reflexive listed as one of its properties/characteristics. I am not sure this works... you explained that "the property means that x spatially_coextensive_with y if and only if x and y have the same location. So the property should be reflexive." Reflexivity, however, is when an entity is reflexive with itself in some way. It would seem that spatially_coextensive_with is not necessarily reflexive in all instances. For example, if x =/= y, then it would not seem to be reflexive. (Or, rather, unless x = y... it wouldn't be reflexive.)

Regarding 1(b), I think you need to add an argument as to why this property is not currently listed as transitive, but should be, along with examples.  (I do realize that this version of your project is not yet finished, but it seems worth to restate this--even as a refresher/reminder for myself...)

Regarding 1(c)... I think this one works, but I am not sure we can (or should) recycle the object properties for our answers in 1(a)--(e). Can you think of a different one for 1(a), esp. since that's the iteration of your answer ('spatially coextensive with') that doesn't seem to work for reflexive. [n.b., you last sentence in 1(c) would seem to apply to 'reflexive' and not 'symmetric,' and thus should be moved to 1(a), if you are going to use this answer in both.]

Regarding 1(d)... interesting answer; I think there might be a typo in '"functional_of should be functional." (Since I am not sure that function_of and functional_of are the same thing.)

Regarding 1(e)... Ok, I see now that you want to use 'spatially coextensive with' in this way; still, see my point about recycling answers above (particularly since it may not work for reflexive...), but then again who knows... perhaps this counts as working smarter instead of harder?(!)
 
Regarding your answer to 2(a)... I am not sure that 'partially overlaps' works for irreflexive. We talked about anti-symmetric vs. asymmetric the other day, and I think a similar insight may apply to 'irreflexive' vs. 'anti-reflexive.' If the stronger version of the two is anti-reflexive, then this might not work, but if it's the other way around then there may not be an issue here.) [[n.b., you still should add an argument for your position.)

Regarding 2(b)...  I am inclined to think that 'aligned with' is fine with Transitive, so this answer would not work for this question. I do wonder to what extent we should be invoking possible worlds against an applied ontology; this reminds me of Smith's text (chp. 3 or 4, or  maybe even earlier), where the book describes a commitment to Realism in ontology.

I'll try and send a second batch of comments later, when you add more answers. (Feel free to tag me in that later version of your project as a reminder!)

**Comment by Jiemingy** [comment]
Hi Emanuel, 
Thank you for the comments!
Sorry that I didn't let you know that I had not completed my answers until now. But your comments are still helpful!
I plan to complete it tonight and will let you know then.  Since I will finish it very late, only leave you one day to look at it. Please feel free if you don't do it. 
Bests,
Jieming

**Review by JaronJCheung — COMMENTED** [review]
Dear Jieming,

Thank you for your invitation to review your Project #3. Below are my thoughts and comments. Please keep what is helpful and discard what is not. 

Q1 (c): I do not know if aligned with is the best candidate for symmetric as it lacks a clear definition. Moreover, I suspect that there are cases where x and y may be aligned at the same line, but lack clear symmetry. Perhaps consider partially overlaps as a good candidate for symmetric. 

Q2 (b): I am not sure about possible worlds being useful to showcase lack of transitivity with regard to aligned with, but perhaps possible worlds can work for applied ontology. I want to ask Professor Beverley about this (lol). 

Q3 (d): To make your answer clear, I recommend hitting enter between each sentence, keeping one space between each sentence blank. This will separate your sentences and help the reader see what your full answer is.

Q4 (a)-(d): I recommend what I wrote for Q3 for all of your answers for Q4 to make them clear.

Q5, Q8, Q9: Please take a look at the Google doc, we have well worked out answers for each of these.

Q10: Nice!

Nice job, Jieming. If you address the aforementioned, you should have a solid Project 3. 

Please let me know if you have any questions. 

Take care, 
Jaron

**Review by peihongx — COMMENTED** [review]
@Jiemingy, here are my comments:

Question 1. (b) “if a branching_part_of b and y branching_part_of c” – Typo: “y” should be revised to “b”

(c) If “aligned with” is symmetric, then it is so **in all cases**. But your argument only shows that it is so **in some cases**. So it is not enough to support your conclusion.

Note: The fact that a relation is not asymmetric does not mean that it is thus symmetric. There is some cases between being asymmetric and being symmetric.  

Q2. (b) “say Many is aligned with Mike in blood relation” – Typo: “Many” should be “Mary”. 

I don’t follow your counterexample: Why “then Otto is not aligned with Mike” if Otto is aligned with Mary in blood, and Mary is also aligned with Mike?

Also, I am not sure whether “aligned with” can apply to the blood relationship. Is it supposed to be a geometric relationship?

(c) "... *be asymmetric to an entity y*" -- I cannot follow what you mean by saying that a characteristic of an entity is asymmetric **to another entity**. Instead, it makes sense if you say a relational quality between x and y is asymmetric per se.

(d) “Take the Moon as an example, not only cold is characteristic of the Moon, but round is also characteristic of the Moon.”

No, you should instead say, “take some property X as an example, it can be characteristic of multiple entities such as a, b, and c.”

Q3. (a) You miss the result: **"Sally participates in having some Arm on some Tuesday" precedes "Sally participates in having no Arm on some Wednesday"**

(c) It seems better if we let "John's childhood", "John's adulthood" and "John's seniorhood" as instances of occurrent. After all, "childhood", "adulthood" and "seniorhood" look more like classes instead of instances.

I think it is needless to say, “¬ (adulthood overlaps seniorhood)”.
(d) Your result looks good, but how can it express “at each point in …”? For me, we should use a **universal conditional** with the form of “∀(G(x)→M(x))” here. Please see our Google Doc file for details.

Q4. (a) **H** should be a three-placed relation between a person, a thing, and a time. In this way, we can model the connection between John's having arm and some time.

(c) It is needless to say, “¬ O (t2, t3)”

Q5. We have a good graph in Google Doc File!

In RDF, we have a triple like (s, p, o), meaning that the subject S is P-related (“p” as a predicate) to the object O. In Mermaid, this triple can be expressed as “A(class/individual name of s) -->|p| B(class/individual name of O)”. So a Mermaid graph can be written in the following way:

```mermaid
graph LR
A(John) -->|instance_of|B(Object)
C(Running) -->|is_a|D(Process)
```

When we assign “graph” as LR, it will unfold from left to right; when we assign it as TD, it will unfold from top to down. “A”, “B” and other capital letters can be used to define nodes in a Mermaid graph.

Q6. (a) Music can be realized in multiple forms, so it should be generically dependent continuant.

(c) BFO does not have “Creature” as class. In fact, if SARS-CoV-2 is a disease, then it can also be a BFO: Disposition.

Furthermore, I recommend to change “instance_of” to “is_a”. “instance_of” is a relation between a particular and a universal, while “is_a” is a relation between a universal/class and a universal class. (a)-(h) are more like classes, so “is_a” is a better choice here.

Q7. (a) Good, although I am unsure whether BFO can deal with the case of Soul.

(b) Justification: According to its definition in BFO, any immaterial entity contains no material entities as parts (Arp, Smith & Spear 2015: 107).

(d) Interesting to say an organization is a role. This is a new idea because BFO usually treats an organization as an Object Aggregate. 

(e) Excellent!

(h) Better to say: Spacetime is the whole of spatiotemporal regions, and the latter belongs to a BFO class: Spatiotemporal Region. 

(i) As its entry in BFO file says, Continuant fiat boundary doesn't have a closure axiom because the subclasses don't necessarily exhaust all possibilities. An example would be the mereological sum of two-dimensional continuant fiat boundary and a one-dimensional continuant fiat boundary that doesn't overlap it.

Q8. We have a good graph in Google Doc File!

Q9. Our Google Doc File has an answer from ChatGPT

Q10. To show the table in its right form, please delete two occurrences of “```”. Two three-dot symbols specify a context of citation where a table cannot show itself in a correct way.

**Comment by Jiemingy** [comment]
Hi Jaron,

Thank you for your comments! Also I appreciate the record of the team meeting on Wednesday: really helps!

Bests,
Jieming

**Comment by Jiemingy** [comment]
Hi Karl,

Thank you for your comments! Also your answers to Q5 and Q10 in Google Doc are super helpful!

Bests,
Jieming

**Pull request merged**
